### GET request to example server
GET http://0.0.0.0:4221
    ?generated-in=GoLand

###
// Request line
POST /files/new.txt HTTP/1.1
Host: localhost:4221
User-Agent: curl/7.64.1
Accept: */*
Content-Type: application/octet-stream  // Header that specifies the format of the request body

12345
###

### Send POST request with json body
POST  /files/argle.txt HTTP/1.1
Content-Type: application/json
Host: localhost:4221
User-Agent: curl/7.64.1
Accept: */*


{
  "id": 999,
  "value": "content"
}